#!/usr/bin/env zsh
###
#
# Add your autostart commands here
# these will run everytime you logon
#
###

# I can't read 1920x1080 resolution.
# change it to the same as my Inspiron:
xrandr --size 1368x768

# helloSystem logs me in -- lucky Balthazar!
# so lock the screen in case it finished 
# loading while I'm in the other room

#catlock --pin 420420 --theme wallpaper &

# testing new prototype
/Applications/Autostart/BadaBing.app/catlock --pin 420420 --tz -3 &